
const headphones = [
    [
        {
            id: 1,
            img: 'byz-s852i.png',
            title: 'Apple BYZ S852I',
            count: 1,
            rate: 4.7,
            price: 2927,
            oldPrice: 3527,
            priceTotal: 2927,
        }, 
        {
            id: 2,
            img: 'earpods.png',
            title: 'Apple EarPods',
            count: 1,
            rate: 4.5,
            price: 2327,
            oldPrice: null,
            priceTotal: 2327,
        }, 
        {
            id: 3,
            img: 'earpods2.png',
            title: 'Apple EarPods',
            count: 1,
            rate: 4.5,
            price: 2327,
            oldPrice: null,
            priceTotal: 2327,
        },
        {
            id: 4,
            img: 'byz-s852i.png',
            title: 'Apple BYZ S852I',
            count: 1,
            rate: 4.7,
            price: 2927,
            oldPrice: null,
            priceTotal: 2927,
        },
        {
            id: 5,
            img: 'earpods.png',
            title: 'Apple EarPods',
            count: 1,
            rate: 4.5,
            price: 2327,
            oldPrice: null,
            priceTotal: 2327,
        },
        {
            id: 6,
            img: 'earpods2.png',
            title: 'Apple EarPods',
            count: 1,
            rate: 4.5,
            price: 2327,
            oldPrice: null,
            priceTotal: 2327,
        },
    ], 
    [
        {
            id: 7,
            img: 'airpods.png',
            title: 'Apple AirPods',
            count: 1,
            rate: 4.7,
            price: 9527,
            oldPrice: null,
            priceTotal: 9527,
        }, 
        {
            id: 8,
            img: 'gerlax-gh-04.png',
            title: 'GERLAX GH-04',
            count: 1,
            rate: 4.7,
            price: 6527,
            oldPrice: null,
            priceTotal: 6527,
        }, 
        {
            id: 9,
            img: 'borofone b04.png',
            title: 'BOROFONE BO4',
            count: 1,
            rate: 4.7,
            price: 7527,
            oldPrice: null,
            priceTotal: 7527,
        },
    ]
]

export default headphones;